#----------------------------------------------------------------------
# This file was generated by c:/Python27/Lib/site-packages/wx-2.9.5-msw/wx/tools/img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAA7lJ"
    "REFUWIWtlk1oHGUYx3/PzGxo2s3ObrPRguihikqhNro1eJE91KJQkSqsBe1FxNQgFBWk9ANL"
    "NCaFSmnB0NKLH9SLEdujIJHmJFQX+iFIBSukUKXNx87upsl2dubxELtkN5vdeUPe28y87//3"
    "m2eemXeEVQztz8QKU+xH9SCKj8qRZG/+SxkkNM2yjOHZrOPdZp+ofixIt4hsQhgpXnn6DQUx"
    "zTNaoP2ZWPEOA4oOgXTVXYMpS+TDxA+/nRPQqJlGFfCmw20KBxrhAALpUPVE8bXte00qEUlA"
    "+zOxydxzne5c6RroKKrzzeatRqKtgGazTvEOA4mqf7oc6066PXIcYWitJOx2cG9jeQD0M5C+"
    "0AofqRadi4kHdbxyl0CRbYIGinTIEpjAeoXn72156J+RP25dG2zBWNGwAd4FoIvNNeZUnf1x"
    "f7owu6HrCbtqx0NL96K8LUJHXUaExmwq0AzeME655/Mf3A+deqkvYa8LvhPhxWVZbSSW9UAE"
    "OKqklx6nf7xUFNErK9xhy56oE4gC/z/1sVKuN91w8oaqLphK1AQiwwFUt4e+PVzYtTWlIJrb"
    "0uHOe1+JyLCphBjDaxJ42OELvt953bEX9sUc+9wG5ma8aucBVT0kIuuaL6vvCVuzWcdLld9F"
    "dDgyHED0HsI3YRibtq3g8yDQPt+2fk5YlfGKxiooFlBS0W5BapWuvaJPbro1suff363CxtL7"
    "wLJvu9FQRIQ9gW+fLNHhuk/lj7tufJct/k5BRlXrd0mBdIh1onA585YlyCEEd9XwumR9Paw6"
    "O2SQUL6eWOg6f/W2htWTCH8vmyr0iMUnlqLGe3gLA1s0cJaesQOnLHC32WyFDkuVT4HCmuBB"
    "VKxXZnKZWkVDh53Ao03oHsIxJzXbNeqlyhXg2Fo8ClV2S5VO79XMT6o8rPCmwPqGWSWQI8np"
    "+JnF1zCXsz3/Rj8wEl1Ci1i6w/c7r8esykWEZyKuK4Ecdmfip2ViomoByNhY4MY2nwUOonjR"
    "cvgLtWfSqZiPMLkaODR8FiNXQpkEcskL+UsA3u5nH1cJvwe2msChYS+IWgmFX9zY5vz9Y/fC"
    "r3+ijJvClwlElhBN3ORmbe/Xo1iwUsVWhkOrH5KWj0NLIB9VnPlvKySCRNV/WZUvRHjABN5S"
    "oL0Ec6p6WQQfpBdImsLbCkSQWGlVJHgkAXOJ6PDIAtElzOBGAu0lzOHGAksk3kEYodZ4WkTl"
    "sDsbP2MCX5UALP7CzaZK71kiR1EsFR1K9sgpOZv3TbP+A5LWKbMmJZczAAAAAElFTkSuQmCC")

geticonIcon = icon.GetIcon
